-- Автогенерировано: сотрудники клиники (пароль по умолчанию 123456789)
INSERT INTO users (full_name, password_hash, must_change_password, role) VALUES
('Абрамов Александр Алексеевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Абрамов Роман Анатольевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Абрамова Наталья Леонидовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Абророва Дилноза Акбархоновна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Агарунов Сергей Сергеевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Адигамова Диана Риязовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Адигамова Диана Риязовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Айдарова Ирина Викторовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Акбарова Гулноза Шодмоновна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Александрова Ирина Викторовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Алемпьева Алина Анатольевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Алибеккадиев Алибеккади Юсупович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Амельченко Елена Анатольевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Анищенко Александр Александрович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Аносенко Вадим Сергеевич Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Антименко Роман Сергеевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Антышева Татьяна Вячеславовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Анюшина Анастасия Васильевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Арестов Андрей Владимирович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Арестов Андрей Владимирович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Архарова Наталья Леонидовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Архарова Наталья Леонидовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Астапенко Анна Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Атаджанова Замира Бекчановна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Атамуротова Насиба Куранбоевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Атамуротова Насиба Куранбоевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Афанасьева Яна Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Баимбетова Зиля Касимовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Балакишиева Гюнель Адалат Кызы', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Батаев Игорь Валентинович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Батманова Юлия Геннадьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Батманова Юлия Геннадьевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Бедрина Наталия Сергеевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Безсмольная Светлана Викторовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Безсмольная Светлана Викторовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Безуглова Кристина Андреевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Белова Юлия Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Белогрудова Лидия Геннадиевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Белозерова Елена Геннадьевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Белоусова Ольга Валентиновна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Белоусова Светлана Алексеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Беляева Ирина Германовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Беляева Юлия Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Бизина Любовь Николаевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Биличенко Светлана Васильевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Битюкова Наталья Ивановна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Блохин Михаил Павлович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Бобков Александр Викторович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Богатова Анастасия Яковлевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Богатова Анастасия Яковлевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Богословская Оксана Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Богословский Петр Владимирович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Больбот Александра Дмитриевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Борисенкова Елена Олеговна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Боровик Наталья Викторовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Бочарова Ксения Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Братанова Алёна Дмитриевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Будзинская Анна Геннадьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Будзинская Анна Геннадьевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Бузаева Елена Владимировна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Бузник Галина Викторовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Бузник Галина Викторовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Буняков Ярослав Александрович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Бутаков Дмитрий Александрович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Бутакова Екатерина Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Быстрова Анна Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Бычкова Марина Леонидовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Вавилов Александр Игоревич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Варваричев Антон Борисович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Варваричев Антон Борисович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Варданян Самвел Валерьевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Варданян Самвел Валерьевич Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Варзилов Ислам', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Варзилов Ислам Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Васильева Анастасия Михайловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Васильева Екатерина Анатольевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Верещако Глеб Анатольевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Верхоглядов Михаил Юрьевич Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Верхоглядова Ольга Ивановна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Веселова Полина Дмитриевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ветлугаева Елена Эдуардовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ветлугаева Елена Эдуардовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ветошкин Вячеслав Андреевич Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Войтенко Дмитрий Андреевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Волков Николай Николаевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Волков Николай Николаевич Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Волкова Дарина Викторовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Волкова Мария Андреевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Вологжанин Дмитрий Александрович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Воронина Лилия Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Воронина Марина Михайловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Воронина Марина Михайловна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Врублевский Николай Михайлович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Выслоух Анна Витальевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ганиева Шохида Зайниддиновна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Гарбузов Евгений Юльевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Герасимова Анна Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Герасимова Анна Николаевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Гигилева Ольга Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Гигилева Ольга Николаевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Гильмуллина Анна Рашитовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Гильмуллина Анна Рашитовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Гладышев Дмитрий Владимирович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Глибчук Сергей Анатольевич Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Гневашева Татьяна Алексеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Гневашева Татьяна Алексеевна Совм.', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Голубчик Наталья Кирилловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Гончарова Раиса Дмитриевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Гончарова Раиса Дмитриевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Гончарова Татьяна Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Гордина Нина Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Гордина Нина Сергеевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Горя Полина Васильевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Горя Полина Васильевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Горяева Дарья Алексеевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Гридина Ксения Евгеньевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Гуров Виктор Иванович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Гусева Оксана Евгеньевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Давыдова Анастасия Алексеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Давыдова Елена Викторовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Даркина Мария Алексеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Дворянова Елена Александровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Деменкова Александра Михайловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Демкович Юлия Александровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Джандагариева Снежана Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Дмитриева Наталья Станиславовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Довжанская Дарья Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Довжанская Дарья Владимировна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Долотказина Светлана Викторовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Дорошенко Ирина Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Дробязго Елена Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Дробязго Елена Владимировна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Дроздовский Роман Богданович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Дроздовский Роман Богданович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Евсеева Анна Сергеевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Егорова Анна Вячеславовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Еженкова Анастасия Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Елагина Ольга Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Емельянов Александр Сергеевич Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ефимов Виктор Алексеевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Жаркой Татьяна Евгеньевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Жаркой Татьяна Евгеньевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Жеглова Елена Валентиновна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Жеглова Елена Валентиновна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Жолдошев Азизбек', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Жукова Татьяна Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Жукова Татьяна Николаевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Жур Настасья Альбертовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Зайнаддинова Зулхумор Мухиддиновна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Зайцева Мария Михайловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Зайцева Наталия Михайловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Зайцева Татьяна Михайловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Залетова Инесса Эдуардовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Залетова Инесса Эдуардовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Замалеева Алина Юрьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Заплавнова Анжелика Евгеньевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Захаров Владимир Владимирович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Захаров Владимир Владимирович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Захарова Мария Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ибодова Елена Леонидовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Иванникова Ирина Анатольевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Иванова Елена Юрьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Иванова Елена Юрьевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Иванова Татьяна Анатольевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Игнатова Татьяна Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ильенко Галина Геннадьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ильенко Галина Геннадьевна Сов', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ильяшова Ирина Германовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Илюхина Оксана Сергеевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Имамутдинов Марат Равилевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Иодис Александр Александрович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Калицун Андрей Анатольевич Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Каменская Анна Юрьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Капустина Анастасия Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Каримова Зулхуморхон Султонхон Кизи', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Каримова Зулхуморхон Султонхон Кизи Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Карпитская Марина Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Карпов Владимир Николаевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Карпова Ирина Витальевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Карташева Елизавета Данииловна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Касаткина Марина Геннадьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Касаткина Марина Геннадьевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кашкарова Варвара Андреевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кириллова Анастасия Кахоровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кирилловых Наталья Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кирилловых Наталья Владимировна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Киселева Анастасия Викторовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Киселева Анастасия Викторовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Клименко Дмитрий Петрович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Клименко Дмитрий Петрович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Коба Светлана Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ковалева Галина Валентиновна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Коваленко Екатерина Вадимовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кожемякина Светлана Александровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Коковкин Вячеслав Олегович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Колесникова Елена Геннадьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Колосарь Алексей Александрович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Колосарь Алексей Александрович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Коптева Юлия Павловна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Корнеева Валентина Васильевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Корниенкова Ирина Александровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Корнильев Станислав Николаевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Корнильева Виктория Андреевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Коробова Юлия Александровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Коробова Юлия Александровна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Королев Сергей Александрович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Короткова Вера Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Короткова Вера Николаевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Косолюкина Екатерина Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Косолюкина Екатерина Николаевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Котлярчук Арина Валерьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Котова Наталия Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кравчук Надежда Михайловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Красноборов Александр Иванович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Криничная Эльвира Эдуардовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кручевская Яна Михайловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Крылов Павел Владимирович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кудрявцева Наталья Михайловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кузнецова Елена Алексеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кузьмин Алексей Ярославович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кузьмин Алексей Ярославович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Куклина Анастасия Вадимовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кулакова Ольга Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кулакова Ольга Николаевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кулебакина Александра Александровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Куприянова Анастасия Валерьевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Куприянова Елизавета Андреевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Куприянова Мария Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Куракина Эльмира Дамировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кучарова Дилбар Джуракуловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кучарова Ойсара Хайдаркуловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Кучумова Екатерина Игоревна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Лазарева Светлана Леонидовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ламан Анна Алексеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ламан Анна Алексеевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Лантухов Дмитрий Викторович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Лантухов Дмитрий Викторович Сов-во', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Лантухов Дмитрий Викторович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ланцова Олеся Павловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ланцова Олеся Павловна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ларина Марина Андреевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Леонова Виталина Вячеславовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Лешуков Сергей Викторович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Лешуков Сергей Викторович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Лимбах Татьяна Константиновна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Лимбах Татьяна Константиновна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Личагина Людмила Петровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Личагина Людмила Петровна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Лодягина Наталья Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ломакина Мария Федоровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Лукина Кристина Игоревна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Любимникова Марина Андреевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Любимникова Марина Андреевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Любимова Наталья Андреевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Майер Светлана Александровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Макарова Алена Юрьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Макарова Елена Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Макарова Елена Сергеевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Макарова Людмила Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Макашева Анна Сергеевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Максимова Ксения Юрьевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Макушкина Анастасия Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Мальцев Николай Павлович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Мальцев Николай Павлович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Мамистова Галина Владиславовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Мамистова Галина Владиславовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Маркова Галина Викторовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Маркова Галина Викторовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Мартынова Анастасия Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Мартынова Анастасия Владимировна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Медведев Герман Владимирович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Меликов Александр Юрьевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Меликов Александр Юрьевич Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Мерзляков Константин Владимирович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Мзокова Зарина Руслановна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Милосердова Лариса Ивановна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Минеева Анастасия Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Мирзакоримова Барнохон Абдусаттаровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Митусова Галина Мариновна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Митусова Галина Мариновна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Михайлова Вера Александровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Михайлова Виктория Евгеньевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Мишкорез Мария Владимировна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Млынская Мария Александровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Млынская Мария Александровна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Можаева Елена Александровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Моисеева Александра Геннадьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Моисеева Александра Геннадьевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Мордовина Александра Валерьевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Мочалова Елена Геннадьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Мочалова Елена Геннадьевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Нагорнева Станислава Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Наркевич Александр Валерьевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Неженцева Елена Леонидовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Некрасова Мария Валентиновна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Нематиллоева Зулфизар Нурмат Кизи', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Нефедов Евгений Юрьевич Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Никитина Светлана Борисовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Николаева Наталья Григорьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Николаенков Игорь Павлович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Никоноров Павел Геннадьевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Никульникова Анастасия Дмитриевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Нилова Кристина Сароевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Новоселова Ирина Евгеньевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Овчинников Петр Петрович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Огай Елена Евгеньевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Озерова Галина Борисовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Омелечко Артем Сергеевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Оноприенко Наталья Геннадьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Осадчук Елена Михайловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Осадчук Елена Михайловна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Османова Софья Алексеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Остапенко Дмитрий Андреевич Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Павленко Лариса Ивановна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Павлов Денис Геннадиевич Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Павлов Никита Максимович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Павлова Виктория Юрьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Падишина Ирина Вячеславовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Падишина Ирина Вячеславовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Палей Дмитрий Борисович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Парасочка Алина Эдуардовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Пастика Юлия Владимировна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Пащенко Наталья Петровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Перелома Екатерина Максимовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Перелома Екатерина Максимовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Петраченко Светлана Александровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Петров Артём Александрович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Петров Кирилл Александрович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Петровская Елена Борисовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Пинтуриа Юлия Михайловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Пинтуриа Юлия Михайловна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Пирогова Кристина Яковлевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Пирогова Кристина Яковлевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Пиронен Галина Игоревна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Позднякова Елизавета Игоревна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Покровская Анастасия Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Полинко Екатерина Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Полинко Екатерина Сергеевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Половникова Ольга Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Половникова Ольга Владимировна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Полуэктова Татьяна Константиновна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Полякова Марина Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Пономарева Екатерина Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Пономаренко Ольга Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Попкова Валентина Анатольевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Попов Дмитрий Владимирович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Попов Сергей Анатольевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Попов Сергей Анатольевич Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Попова Виктория Дмитриевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Путренкова Ирина Алексеевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Пухова Вера Ивановна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Пухова Вера Ивановна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Пшеничка Галина Евгеньевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Пшеничка Галина Евгеньевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Раджапова Гузал Назировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ракул Сергей Анатольевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Резниченко Александра Александровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Репина Ольга Анатольевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Рогожина Виктория Алексеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Родиченко Виктория Викторовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Романова Елена Викторовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Романова Татьяна Валерьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Романова Юлия Вячеславовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Романова Юлия Вячеславовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Романченко Екатерина Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Рубцова Мария Валерьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Руденко Екатерина Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Руденко Екатерина Николаевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Рудь Людмила Михайловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Рудь Людмила Михайловна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Рушакова Светлана Витальевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Рыженкова Инна Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Рябоус Елена Анатольевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Саад Антон Элиасович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Саад Антон Элиасович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Саад Кристина Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Сабура Алена Викторовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Сабура Алена Викторовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Савенко Виктория Олеговна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Савилов Андрей Николаевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Садиева Лола Алохидиновна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Садикова Фируза Анваровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Садикова Фируза Анваровна Сов', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Садыкова Алла Юрьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Сарана Егор Андреевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Сафарян Оксана Васильевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Свистунова Полина Валентиновна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Свистунова Полина Валентиновна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Селезнева Наталья Владимировна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Семенова Елена Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Семиврагова Ольга Геннадьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Сергеев Евгений Алексеевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Сергеев Евгений Алексеевич Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Серогодская Татьяна Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Серогодская Татьяна Николаевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Скребкова Наталья Александровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Скуридин Даниил Сергеевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Скуридин Даниил Сергеевич Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Смирнова Мария Яковлевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Смолян Владимир Дмитриевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Смотрова Ксения Петровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Солод Ольга Борисовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Солодовникова Нелля Григорьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Солодовникова Нелля Григорьевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Соломицкий Денис Николаевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Сопилова Оксана Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Сорокина Наталья Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Сорокина Наталья Яковлевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Сорокина Наталья Яковлевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Спирин Анатолий Борисович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Спицына Наталья Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Спицына Наталья Николаевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Спыну Светлана Ивановна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Стальцева Наталия Николаевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Стальцева Наталия Николаевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Старков Александр Николаевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Степанов Алексей Юрьевич Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Стогний Юлия Львовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Стогний Юлия Львовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Тверитнева Татьяна Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Тверитнева Татьяна Владимировна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Телегин Константин Петрович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Теренин Виталий Станиславович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Терехина Инна Викторовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Терехина Инна Викторовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Титова Анастасия Юрьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Титова Анастасия Юрьевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Торопова Юлия Валентиновна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Торопова Юлия Валентиновна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Трофименко Ксения Станиславовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Трусов Иван Александрович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Узокова Кубарро Исроил Кизи', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Узокова Кубарро Исроил Кизи Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Улугова Эсаной Тойировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Урманова Виктория Валерьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Флегонтова Анна Валерьевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Фролова Диана Юрьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Хаитбаева Танзиля Шавкатовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Хаитбаева Танзиля Шавкатовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Хайкина Яна Валерьевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Харина Ольга Игоревна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Харькова Дарья Юрьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Харькова Дарья Юрьевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Хасанова Марифат Бахтиёр Кизи', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Хасанова Насиба Насимовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Хоботникова Светлана Романовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Холбоева Дилобар Тошниёзовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Хоромец Олеся Викторовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Хоромец Олеся Викторовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Цветкова Ирина Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Цивьян Борис Львович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Цивьян Борис Львович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Цыпурдеева Анна Алексеевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Чеботарева Мария Алексеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Чемезова Наталья Александровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Чемезова Наталья Александровна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Черемисина Людмила Борисовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Черемисина Людмила Борисовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Черкасова Лола Муратовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Черкасова Лола Муратовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шалимова Анастасия Павловна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шамсиева Хулкар Тоировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шамсиева Хулкар Тоировна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шамуратова Зарина Мухаммедовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шамуратова Зарина Мухаммедовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шаров Владимир Олегович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шаров Владимир Олегович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шарофова Парвина Дилшод кизи', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Швец Федор Владимирович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Швец Федор Владимирович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шевцова Ирина Андреевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шевцова Ирина Андреевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шевчук Екатерина Игоревна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шемякин Игорь Олегович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шендерова Лидия Евгеньевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шестакова Алина Сергеевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шестакова Алина Сергеевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шилина Александра Петровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ширяева Екатерина Вячеславовна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Ширяева Екатерина Вячеславовна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шишмаркина Ирина Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шмидт Андрей Александрович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Шмидт Андрей Александрович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Энтина Елена Витальевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Энтина Елена Витальевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Эртман Полина Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Эртман Полина Владимировна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Эфендиев Алексей Октаевич', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Юдина Вера Сергеевна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Юлдашев Дилшодбек Максудбекович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Юмашева Ольга Александровна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Юферов Александр Вячеславович', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Юферов Александр Вячеславович Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Яблочко Анастасия Андреевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Яковенко Татьяна Петровна Совм', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Яковлева Алла Владимировна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Яковлева Анна Валерьевна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee'),
('Якубова Ирина Александровна', '$2y$12$2.vXKYPquFojxB.ozZ4SGuKcAdyQZKbXUKzMOSWTsKb4YNQhwZgYW', 1, 'employee');
